// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import context "context"

import mock "github.com/stretchr/testify/mock"
import model "github.com/kyma-incubator/compass/components/director/internal/model"

// LabelRepository is an autogenerated mock type for the LabelRepository type
type LabelRepository struct {
	mock.Mock
}

// Upsert provides a mock function with given fields: ctx, tenant, objectType, objectID, _a4
func (_m *LabelRepository) Upsert(ctx context.Context, tenant string, objectType model.LabelableObject, objectID string, _a4 *model.Label) error {
	ret := _m.Called(ctx, tenant, objectType, objectID, _a4)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.LabelableObject, string, *model.Label) error); ok {
		r0 = rf(ctx, tenant, objectType, objectID, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
